import turtle
import time

def drawSqaure(t, color, penWidth):
    """ my function
    """
    t.color(color)
    t.width(penWidth)

    t.forward(300)
    t.right(90)
    t.forward(300)
    t.right(90)
    t.forward(300)
    t.right(90)
    t.forward(300)
    t.right(90)    

    return True


t=turtle.Turtle()
t.shape("turtle")

t.speed(10)

drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "orange", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 48)
drawSqaure(t, "blue", 24)
drawSqaure(t, "red", 12)
drawSqaure(t, "blue", 6)
drawSqaure(t, "orange", 3)
drawSqaure(t, "blue", 1)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "greene", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "orange", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 48)
drawSqaure(t, "blue", 24)
drawSqaure(t, "red", 12)
drawSqaure(t, "blue", 6)
drawSqaure(t, "orange", 3)
drawSqaure(t, "blue", 1)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "greene", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "orange", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 48)
drawSqaure(t, "blue", 24)
drawSqaure(t, "red", 12)
drawSqaure(t, "blue", 6)
drawSqaure(t, "orange", 3)
drawSqaure(t, "blue", 1)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "greene", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "orange", 30)
drawSqaure(t, "blue", 15)
drawSqaure(t, "red", 48)
drawSqaure(t, "blue", 24)
drawSqaure(t, "red", 12)
drawSqaure(t, "blue", 6)
drawSqaure(t, "orange", 3)
drawSqaure(t, "blue", 1)
drawSqaure(t, "red", 480)
drawSqaure(t, "blue", 240)
drawSqaure(t, "red", 120)
drawSqaure(t, "blue", 60)
drawSqaure(t, "greene", 30)
drawSqaure(t, "blue", 15)